In [2]:
import pandas as pd
import numpy as np

In [3]:
df_raw = pd.read_parquet('./preprocessed.parquet.gzip')

In [4]:
df_raw

,case_id,date_decision,MONTH,WEEK_NUM,target,datelastunpaid_3546854D,bankacctype_710L,cardtype_51L,cntincpaycont9m_3716944L,cntpmts24_3658933L,...,numinstregularpaid_973L.1,numinsttopaygr_769L.1,numinstunpaidmax_3546851L.1,pmtnum_254L.1,posfpd30lastmonth_3976960P.1,price_1097A.1,sumoutstandtotal_3546847A.1,totaldebt_9A.1,totalsettled_863A.1,time_delta
0,0,2019-01-03,201901,0,0,2019-01-03,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.00,15384.0
1,1,2019-01-03,201901,0,0,2019-01-03,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.00,15384.0
2,2,2019-01-04,201901,0,0,2019-01-04,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.00,15360.0
3,3,2019-01-03,201901,0,0,2019-01-03,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.00,15384.0
4,4,2019-01-04,201901,0,1,2019-01-04,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.00,15360.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526654,2703450,2020-10-05,202010,91,0,2016-09-15,CA,NOCARD,15.0,24.0,...,113.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,428159.66,35544.0
1526655,2703451,2020-10-05,202010,91,0,2020-05-30,CA,NOCARD,17.0,21.0,...,75.0,11.0,11.0,24.0,0.0,0.0,68098.4,68098.4,701247.30,3072.0
1526656,2703452,2020-10-05,202010,91,0,2019-03-16,CA,NOCARD,0.0,7.0,...,9.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,24002.00,13656.0
1526657,2703453,2020-10-05,202010,91,0,2018-01-15,CA,NOCARD,7.0,23.0,...,115.0,17.0,17.0,6.0,0.0,0.0,46806.6,46806.6,440145.30,23856.0
1526658,2703454,2020-10-05,202010,91,0,2019-09-01,CA,NOCARD,10.0,14.0,...,15.0,3.0,3.0,12.0,0.0,0.0,8919.2,5919.2,92999.57,9600.0

In [5]:
(df_raw.memory_usage().sum())/(1024*1024)

1435.5525035858154

In [6]:
df_raw['target'].describe()

count    1.526659e+06
mean     3.143728e-02
std      1.744964e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: target, dtype: float64

In [7]:
df_raw[df_raw['target'] == 1]

,case_id,date_decision,MONTH,WEEK_NUM,target,datelastunpaid_3546854D,bankacctype_710L,cardtype_51L,cntincpaycont9m_3716944L,cntpmts24_3658933L,...,numinstregularpaid_973L.1,numinsttopaygr_769L.1,numinstunpaidmax_3546851L.1,pmtnum_254L.1,posfpd30lastmonth_3976960P.1,price_1097A.1,sumoutstandtotal_3546847A.1,totaldebt_9A.1,totalsettled_863A.1,time_delta
4,4,2019-01-04,201901,0,1,2019-01-04,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.000,15360.0
101,101,2019-01-03,201901,0,1,2019-01-03,CA,NOCARD,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.000,15384.0
118,118,2019-01-03,201901,0,1,2019-01-03,CA,INSTANT,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,15392.0,0.0,0.0,0.000,15384.0
129,129,2019-01-04,201901,0,1,2019-01-04,CA,NOCARD,0.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.000,15360.0
148,148,2019-01-04,201901,0,1,2019-01-04,CA,INSTANT,0.0,0.0,...,0.0,0.0,0.0,6.0,0.0,11440.0,0.0,0.0,0.000,15360.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526128,2702884,2020-10-02,202010,91,1,2019-04-24,None,INSTANT,0.0,5.0,...,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13152.229,12720.0
1526147,2702904,2020-10-02,202010,91,1,2019-08-29,CA,NOCARD,8.0,21.0,...,135.0,16.0,16.0,24.0,0.0,0.0,109454.2,109454.2,598097.200,9672.0
1526245,2703005,2020-10-03,202010,91,1,2017-05-08,None,INSTANT,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76544.000,29904.0
1526608,2703400,2020-10-05,202010,91,1,2019-12-07,CA,NOCARD,7.0,19.0,...,53.0,0.0,0.0,44.0,0.0,0.0,0.0,0.0,148302.610,7272.0
1526618,2703411,2020-10-05,202010,91,1,2017-01-10,CA,NOCARD,0.0,0.0,...,6.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,24200.000,32736.0

In [8]:
df_raw.dtypes

case_id                          int64
date_decision                   object
MONTH                            int64
WEEK_NUM                         int64
target                           int64
                                ...
price_1097A.1                  float64
sumoutstandtotal_3546847A.1    float64
totaldebt_9A.1                 float64
totalsettled_863A.1            float64
time_delta                     float64
Length: 125, dtype: object

In [9]:
df_raw[df_raw['target'] == 0].sample(n=47994, random_state=45)

,case_id,date_decision,MONTH,WEEK_NUM,target,datelastunpaid_3546854D,bankacctype_710L,cardtype_51L,cntincpaycont9m_3716944L,cntpmts24_3658933L,...,numinstregularpaid_973L.1,numinsttopaygr_769L.1,numinstunpaidmax_3546851L.1,pmtnum_254L.1,posfpd30lastmonth_3976960P.1,price_1097A.1,sumoutstandtotal_3546847A.1,totaldebt_9A.1,totalsettled_863A.1,time_delta
325982,710515,2019-06-11,201906,23,0,2019-06-11,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,37980.0,0.0000,0.000,0.000,11568.0
668441,1262470,2019-01-23,201901,3,0,2019-01-23,CA,NOCARD,0.0,7.0,...,7.0,0.0,0.0,12.0,0.0,26800.0,0.0000,0.000,28240.000,14904.0
1145693,1739722,2020-01-08,202001,53,0,2019-12-03,None,NOCARD,9.0,24.0,...,28.0,0.0,0.0,12.0,0.0,26998.0,5290.8003,6356.000,48388.402,7368.0
105497,150931,2019-08-13,201908,32,0,2018-04-07,CA,NOCARD,0.0,11.0,...,41.0,0.0,0.0,24.0,0.0,0.0,0.0000,0.000,165531.200,21888.0
298899,683432,2019-04-30,201904,17,0,2019-04-30,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,53213.8,0.0000,0.000,0.000,12576.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008971,1603000,2019-10-29,201910,43,0,2019-10-03,None,NOCARD,10.0,25.0,...,42.0,15.0,15.0,36.0,0.0,168000.0,73311.8050,73311.805,186207.000,8832.0
810111,1404140,2019-06-14,201906,23,0,2007-06-09,None,NOCARD,10.0,12.0,...,18.0,4.0,4.0,12.0,0.0,26674.0,14445.6010,14445.601,86276.600,116808.0
1011701,1605730,2019-11-01,201911,43,0,2014-11-19,None,NOCARD,2.0,12.0,...,24.0,0.0,0.0,24.0,0.0,237974.0,0.0000,0.000,193840.000,51528.0
1255647,1849676,2020-05-29,202005,73,0,2020-05-29,None,NOCARD,10.0,6.0,...,22.0,14.0,8.0,12.0,0.0,39978.0,20854.0000,20854.000,56880.000,3096.0
658221,1252250,2019-01-19,201901,2,0,2018-05-18,CA,NOCARD,11.0,21.0,...,72.0,0.0,0.0,6.0,0.0,18580.0,0.0000,0.000,188078.610,20904.0

In [10]:
union_df = pd.concat([df_raw[df_raw['target'] == 1], df_raw[df_raw['target'] == 0].sample(n=47994, random_state=45)], ignore_index=True)

In [11]:
union_df

,case_id,date_decision,MONTH,WEEK_NUM,target,datelastunpaid_3546854D,bankacctype_710L,cardtype_51L,cntincpaycont9m_3716944L,cntpmts24_3658933L,...,numinstregularpaid_973L.1,numinsttopaygr_769L.1,numinstunpaidmax_3546851L.1,pmtnum_254L.1,posfpd30lastmonth_3976960P.1,price_1097A.1,sumoutstandtotal_3546847A.1,totaldebt_9A.1,totalsettled_863A.1,time_delta
0,4,2019-01-04,201901,0,1,2019-01-04,None,NOCARD,0.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.000,0.000,0.00,15360.0
1,101,2019-01-03,201901,0,1,2019-01-03,CA,NOCARD,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,0.0,0.000,0.000,0.00,15384.0
2,118,2019-01-03,201901,0,1,2019-01-03,CA,INSTANT,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,15392.0,0.000,0.000,0.00,15384.0
3,129,2019-01-04,201901,0,1,2019-01-04,CA,NOCARD,0.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.000,0.000,0.00,15360.0
4,148,2019-01-04,201901,0,1,2019-01-04,CA,INSTANT,0.0,0.0,...,0.0,0.0,0.0,6.0,0.0,11440.0,0.000,0.000,0.00,15360.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95983,1603000,2019-10-29,201910,43,0,2019-10-03,None,NOCARD,10.0,25.0,...,42.0,15.0,15.0,36.0,0.0,168000.0,73311.805,73311.805,186207.00,8832.0
95984,1404140,2019-06-14,201906,23,0,2007-06-09,None,NOCARD,10.0,12.0,...,18.0,4.0,4.0,12.0,0.0,26674.0,14445.601,14445.601,86276.60,116808.0
95985,1605730,2019-11-01,201911,43,0,2014-11-19,None,NOCARD,2.0,12.0,...,24.0,0.0,0.0,24.0,0.0,237974.0,0.000,0.000,193840.00,51528.0
95986,1849676,2020-05-29,202005,73,0,2020-05-29,None,NOCARD,10.0,6.0,...,22.0,14.0,8.0,12.0,0.0,39978.0,20854.000,20854.000,56880.00,3096.0
95987,1252250,2019-01-19,201901,2,0,2018-05-18,CA,NOCARD,11.0,21.0,...,72.0,0.0,0.0,6.0,0.0,18580.0,0.000,0.000,188078.61,20904.0

In [12]:
(union_df.memory_usage().sum())/(1024*1024)

90.25983428955078

In [13]:
transformed_df = union_df.drop(columns=['maxdbddpdtollast6m_4187119P'], inplace=False).copy()

In [14]:
cat_columns = transformed_df.select_dtypes(include=['object', 'bool'])
num_columns = transformed_df.select_dtypes(exclude=['object', 'bool'])

In [15]:
num_columns_list = num_columns.columns.to_list()
cat_columns_list = cat_columns.columns.to_list()

In [16]:
exclude_list = ['case_id','target', 'MONTH', 'WEEK_NUM']
exclude_num_list = list(filter(lambda i: i not in exclude_list, num_columns_list))
cat_exclude_list = ['datelastunpaid_3546854D','date_decision']
exclude_cat_list = list(filter(lambda i: i not in cat_exclude_list, cat_columns_list))

In [17]:
exclude_cat_list

['bankacctype_710L',
 'cardtype_51L',
 'inittransactioncode_186L',
 'lastst_736L',
 'opencred_647L',
 'credtype_322L',
 'disbursementtype_67L',
 'isbidproduct_1095L',
 'lastapprcommoditycat_1041M',
 'lastapprcommoditytypec_5251766M',
 'lastcancelreason_561M',
 'lastrejectcommoditycat_161M',
 'lastrejectcommodtypec_5251769M',
 'lastrejectreason_759M',
 'lastrejectreasonclient_4145040M',
 'previouscontdistrict_112M']

In [18]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

df_scaled = std_scaler.fit_transform(transformed_df[exclude_num_list].to_numpy())
df_scaled = pd.DataFrame(df_scaled, columns=exclude_num_list)

In [19]:
main_scaled = pd.concat([transformed_df[exclude_list], df_scaled], axis=1, join="inner")

In [20]:
main_cat = transformed_df[exclude_cat_list].copy()

In [21]:
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2 
from sklearn.datasets import load_iris 
from sklearn.preprocessing import LabelEncoder

In [22]:
label_encoder = LabelEncoder()
for col in main_cat.columns:
    main_cat[col] = label_encoder.fit_transform(main_cat[col])

In [23]:
combined_df = pd.concat([main_scaled, main_cat], axis=1, join="inner")

In [24]:
combined_df

,case_id,target,MONTH,WEEK_NUM,cntincpaycont9m_3716944L,cntpmts24_3658933L,commnoinclast6m_3546845L,eir_270L,interestrate_311L,lastapprcredamount_781A,...,disbursementtype_67L,isbidproduct_1095L,lastapprcommoditycat_1041M,lastapprcommoditytypec_5251766M,lastcancelreason_561M,lastrejectcommoditycat_161M,lastrejectcommodtypec_5251769M,lastrejectreason_759M,lastrejectreasonclient_4145040M,previouscontdistrict_112M
0,4,1,201901,0,-0.731513,-0.885906,0.0,0.934709,0.894569,-0.732621,...,1,0,33,85,33,35,84,17,10,221
1,101,1,201901,0,-0.731513,-0.885906,0.0,0.934709,0.894569,-0.732621,...,1,0,33,85,52,35,84,15,10,221
2,118,1,201901,0,-0.731513,-0.885906,0.0,-0.428507,-0.060213,-0.732621,...,2,0,33,85,57,35,84,17,10,221
3,129,1,201901,0,-0.731513,-0.885906,0.0,0.934709,0.894569,-0.732621,...,1,0,33,85,57,35,84,17,10,221
4,148,1,201901,0,-0.731513,-0.885906,0.0,-0.428507,-0.060213,-0.732621,...,2,0,33,85,57,35,84,17,10,221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95983,1603000,0,201910,43,1.008388,2.288709,0.0,0.591179,0.546645,1.529718,...,2,0,33,85,52,14,84,4,9,30
95984,1404140,0,201906,23,1.008388,0.637909,0.0,-1.519080,-1.590607,0.494528,...,2,0,6,85,57,10,84,17,10,205
95985,1605730,0,201911,43,-0.383533,0.637909,0.0,-1.519080,-1.590607,2.095303,...,2,0,33,85,52,35,84,15,9,180
95986,1849676,0,202005,73,1.008388,-0.123999,0.0,0.757491,0.715085,-0.405317,...,2,0,33,85,57,35,84,17,10,190
95987,1252250,0,201901,2,1.182378,1.780770,0.0,-1.512536,-1.583979,0.228817,...,2,0,14,85,57,35,84,17,10,171

In [25]:
X = combined_df.drop(columns =['target'], inplace=False).to_numpy()

In [26]:
all_columns_list = combined_df.drop(columns =['target'], inplace=False).columns.to_list()

In [27]:
y= combined_df['target'].to_numpy()

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [29]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, step = 20, n_features_to_select=20)
fit = rfe.fit(x_train, y_train)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 20
Selected Features: [ True  True False False False False False False False  True False False
 False  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
  True False False False  True False False False  True False False  True
  True False False False False False False False False False False False
 False False False False False  True False False False  True  True False
 False False False False False False False False False False False False
 False False False False False False  True  True  True  True  True  True
  True]
Feature Ranking: [1 1 5 6 4 7 4 4 7 1 7 5 4 1 1 3 4 4 3 6 4 4 4 3 7 3 5 6 7 3 7 7 7 5 3 4 3
 3 5 3 5 6 6 6 6 5 6 6 7 5 7 5 6 7 6 6 6 3 4 5 1 7 3 6 1 5 5 6 1 5 6 1 1 5
 2 6 5 3 5 3 3 4 3 3 7 6 4 7 7 1 7 5 4 1 1 3 4 4 3 6 4 4 4 3 5 7 7 5 3 7 6
 5 7 4 1 1 1 1 1 1 1]

In [30]:
df_column_pairs = pd.DataFrame({'column_name': all_columns_list, 'condition': fit.support_})

In [31]:
top_20_cols = df_column_pairs[df_column_pairs['condition']]['column_name'].to_list()

In [32]:
top_20_cols

['case_id',
 'MONTH',
 'lastrejectcredamount_222A',
 'numinstlsallpaid_934L',
 'numinstpaidearly_338L',
 'daysoverduetolerancedd_3976961L',
 'mobilephncnt_593L',
 'numcontrs3months_479L',
 'numrejects9m_859L',
 'sellerplacecnt_915L',
 'lastrejectcredamount_222A.1',
 'numinstlsallpaid_934L.1',
 'numinstpaidearly_338L.1',
 'lastapprcommoditytypec_5251766M',
 'lastcancelreason_561M',
 'lastrejectcommoditycat_161M',
 'lastrejectcommodtypec_5251769M',
 'lastrejectreason_759M',
 'lastrejectreasonclient_4145040M',
 'previouscontdistrict_112M']

In [42]:
heir_raw = pd.DataFrame(x_train, columns =all_columns_list ).set_index('case_id', inplace=False)

In [43]:
heir_raw

,MONTH,WEEK_NUM,cntincpaycont9m_3716944L,cntpmts24_3658933L,commnoinclast6m_3546845L,eir_270L,interestrate_311L,lastapprcredamount_781A,lastrejectcredamount_222A,maininc_215A,...,disbursementtype_67L,isbidproduct_1095L,lastapprcommoditycat_1041M,lastapprcommoditytypec_5251766M,lastcancelreason_561M,lastrejectcommoditycat_161M,lastrejectcommodtypec_5251769M,lastrejectreason_759M,lastrejectreasonclient_4145040M,previouscontdistrict_112M
case_id,,,,,,,,,,,,,,,,,,,,,
105588.0,201901.0,2.0,0.138437,-0.123999,0.0,0.934709,0.894569,2.095303,-0.616854,0.788424,...,1.0,0.0,33.0,85.0,57.0,35.0,84.0,17.0,10.0,136.0
2608648.0,201908.0,32.0,-0.731513,-0.885906,0.0,0.771123,0.728891,0.115756,0.600801,-0.829664,...,1.0,1.0,33.0,85.0,57.0,35.0,84.0,17.0,10.0,8.0
2583138.0,201906.0,23.0,0.660408,2.288709,0.0,0.771123,0.728891,2.095303,-0.089203,2.049867,...,1.0,1.0,33.0,85.0,18.0,35.0,84.0,17.0,10.0,171.0
1358817.0,201905.0,17.0,-0.731513,-0.758922,0.0,0.825652,0.784117,-0.370647,-0.464485,-0.272336,...,2.0,0.0,6.0,85.0,57.0,29.0,84.0,15.0,9.0,168.0
1314891.0,201903.0,11.0,0.834398,0.256955,0.0,0.607537,0.563213,-0.376868,-0.616854,-0.243666,...,2.0,0.0,6.0,85.0,57.0,35.0,84.0,17.0,10.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214133.0,202003.0,61.0,1.182378,0.256955,0.0,0.934709,0.894569,1.360043,0.194916,0.845762,...,1.0,0.0,33.0,85.0,52.0,35.0,84.0,7.0,9.0,25.0
749026.0,201907.0,28.0,-0.731513,-0.885906,0.0,0.607537,0.563213,-0.732621,-0.616854,-0.931727,...,2.0,0.0,33.0,85.0,57.0,35.0,84.0,17.0,10.0,221.0
1770557.0,202002.0,56.0,1.182378,0.129970,0.0,0.607537,0.563213,-0.280153,-0.616854,0.215040,...,2.0,0.0,33.0,85.0,57.0,35.0,84.0,17.0,10.0,35.0
30218.0,201909.0,36.0,-0.731513,-0.885906,0.0,-0.428507,-0.060213,-0.732621,0.194916,-0.931727,...,0.0,0.0,33.0,85.0,52.0,35.0,84.0,7.0,9.0,221.0
895178.0,201912.0,49.0,-0.731513,-0.885906,0.0,0.934709,0.894569,-0.732621,-0.616854,-0.931727,...,2.0,0.0,33.0,85.0,57.0,35.0,84.0,17.0,10.0,221.0

In [44]:
heir_raw.to_parquet('heir_raw_refactored.parquet')

In [45]:
series_actual = pd.Series(y_train)

In [46]:
y_train_df = pd.DataFrame({'actual': series_actual})
y_train_df.to_parquet('actual_refactored.parquet')